version: '3'

volumes:
  shopping_mall_local_postgres_data: {}
  shopping_mall_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: shopping_mall_local_django
    container_name: shopping_mall_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '80:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: shopping_mall_production_postgres
    container_name: shopping_mall_local_postgres
    volumes:
      - shopping_mall_local_postgres_data:/var/lib/postgresql/data
      - shopping_mall_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
